version: '3.8'

services:
  empleados-db:
    image: postgres:latest
    container_name: empleados-db
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: empleados
    ports: 
      - "5432:5432"
    volumes:
      - empleados_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  empleados_db_data: